namespace Assets.Scripts.Logic
{
    public static class StatUtils
    {
        public static float CombineStat(StatType type, float first, float second)
        {
            // Todo
            return first + second;
        }

        // damage adjustment is =LN(x^2+1)*5 <-- where x is the damage score generated by the weapon
    }
}
